// <auto-generated />
using System;
using FixIt.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FixIt.Infrastructure.Migrations
{
    [DbContext(typeof(FixItDbContext))]
    [Migration("20260919181701_AgregarAdjuntosChat")]
    partial class AgregarAdjuntosChat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FixIt.Domain.Entities.Calificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("Calidad")
                        .HasColumnType("smallint");

                    b.Property<string>("Comentario")
                        .HasColumnType("text");

                    b.Property<short>("Comunicacion")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Garantia")
                        .HasColumnType("smallint");

                    b.Property<short>("Limpieza")
                        .HasColumnType("smallint");

                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uuid");

                    b.Property<short>("Precio")
                        .HasColumnType("smallint");

                    b.Property<short>("Puntualidad")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("Calificaciones");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("boolean");

                    b.Property<string>("Icono")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Conversacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PrestadorId");

                    b.HasIndex("ClienteId", "PrestadorId", "CategoriaId");

                    b.ToTable("Conversaciones");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.DisponibilidadPrestador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("Disponibilidad");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.FotoTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("FotosTrabajo");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Mensaje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArchivoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Contenido")
                        .HasColumnType("text");

                    b.Property<Guid>("ConversacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DescripcionOferta")
                        .HasColumnType("text");

                    b.Property<int?>("DuracionSegundos")
                        .HasColumnType("integer");

                    b.Property<Guid>("EmisorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("EnviadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Leido")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MontoOferta")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset?>("OfertaExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("OfertaPagada")
                        .HasColumnType("boolean");

                    b.Property<bool>("OfertaVigente")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("OrdenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("EmisorId");

                    b.HasIndex("OrdenId");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Orden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ComisionPlataforma")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<DateTimeOffset?>("CompletadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConversacionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("FechaHoraProgramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MensajeOfertaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MontoTotal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ConversacionId");

                    b.HasIndex("PrestadorId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Pago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("LiberadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasColumnType("text");

                    b.Property<decimal>("Monto")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("OrdenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrdenId")
                        .IsUnique();

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.PrestadorCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<decimal?>("PrecioReferencia")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("PrestadorId", "CategoriaId")
                        .IsUnique();

                    b.ToTable("PrestadorCategorias");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.SuscripcionPush", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("SuscripcionesPush");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AntecedentesPenalesUrl")
                        .HasColumnType("text");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Biografia")
                        .HasColumnType("text");

                    b.Property<string>("CodigoVerificacionEmail")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CodigoVerificacionExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<double?>("DireccionLat")
                        .HasColumnType("double precision");

                    b.Property<double?>("DireccionLon")
                        .HasColumnType("double precision");

                    b.Property<bool>("DireccionVerificada")
                        .HasColumnType("boolean");

                    b.Property<string>("DniFotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("DniNumero")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmado")
                        .HasColumnType("boolean");

                    b.Property<int>("EstadoVerificacion")
                        .HasColumnType("integer");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("text");

                    b.Property<double?>("Latitud")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitud")
                        .HasColumnType("double precision");

                    b.Property<string>("MatriculaUrl")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoAccessToken")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoOAuthState")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("MercadoPagoOAuthStateExpira")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MercadoPagoRefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("MercadoPagoTokenExpiraEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MercadoPagoUserId")
                        .HasColumnType("text");

                    b.Property<string>("MotivoRechazoVerificacion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RadioAlcanceKm")
                        .HasColumnType("integer");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrabajosPagados")
                        .HasColumnType("integer");

                    b.Property<bool>("TutorialVisto")
                        .HasColumnType("boolean");

                    b.Property<Point>("UbicacionGeo")
                        .HasColumnType("geography (point)");

                    b.Property<DateTimeOffset?>("VerificacionEnviadaEn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verificado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Rol");

                    b.HasIndex("UbicacionGeo");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("UbicacionGeo"), "GIST");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Calificacion", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Orden", "Orden")
                        .WithOne("Calificacion")
                        .HasForeignKey("FixIt.Domain.Entities.Calificacion", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Conversacion", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FixIt.Domain.Entities.Usuario", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FixIt.Domain.Entities.Usuario", "Prestador")
                        .WithMany()
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cliente");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.DisponibilidadPrestador", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Usuario", "Prestador")
                        .WithMany("Disponibilidad")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.FotoTrabajo", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Usuario", "Prestador")
                        .WithMany("FotosTrabajo")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Mensaje", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany("Mensajes")
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FixIt.Domain.Entities.Usuario", "Emisor")
                        .WithMany("Mensajes")
                        .HasForeignKey("EmisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FixIt.Domain.Entities.Orden", null)
                        .WithMany("Mensajes")
                        .HasForeignKey("OrdenId");

                    b.Navigation("Conversacion");

                    b.Navigation("Emisor");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Orden", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FixIt.Domain.Entities.Usuario", "Cliente")
                        .WithMany("OrdenesComoCliente")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FixIt.Domain.Entities.Conversacion", "Conversacion")
                        .WithMany()
                        .HasForeignKey("ConversacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FixIt.Domain.Entities.Usuario", "Prestador")
                        .WithMany("OrdenesComoPrestador")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Cliente");

                    b.Navigation("Conversacion");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Pago", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Orden", "Orden")
                        .WithOne("Pago")
                        .HasForeignKey("FixIt.Domain.Entities.Pago", "OrdenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orden");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.PrestadorCategoria", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Categoria", "Categoria")
                        .WithMany("PrestadorCategorias")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FixIt.Domain.Entities.Usuario", "Prestador")
                        .WithMany("PrestadorCategorias")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.SuscripcionPush", b =>
                {
                    b.HasOne("FixIt.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("PrestadorCategorias");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Conversacion", b =>
                {
                    b.Navigation("Mensajes");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Orden", b =>
                {
                    b.Navigation("Calificacion");

                    b.Navigation("Mensajes");

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("FixIt.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Disponibilidad");

                    b.Navigation("FotosTrabajo");

                    b.Navigation("Mensajes");

                    b.Navigation("OrdenesComoCliente");

                    b.Navigation("OrdenesComoPrestador");

                    b.Navigation("PrestadorCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
